//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KlinikApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Examination
    {
        public int Ex_Id { get; set; }
        public string Ex_Exam { get; set; }
        public System.DateTime Ex_Date { get; set; }
        public int Ex_Patient { get; set; }
        public int Ex_Employee { get; set; }
        public string Ex_Klinik { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Examtype Examtype { get; set; }
        public virtual Klinik Klinik { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
