//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KlinikApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Klinik
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Klinik()
        {
            this.Employees = new HashSet<Employee>();
            this.Examinations = new HashSet<Examination>();
        }
    
        public string K_Id { get; set; }
        public string K_Address { get; set; }
        public int K_Plz { get; set; }
        public string K_Ort { get; set; }
        public string K_Bundesland { get; set; }
    
        public virtual Bundesland Bundesland { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee> Employees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Examination> Examinations { get; set; }
    }
}
